### PR TITLE
Downgraded .NET version for better compatibility

### PR DESCRIPTION
**Pull request by atruskie**
Hi, cool project.

I'm using an older version of .NET. As far as I can tell there's no need for this library to rely on .NET 4.6.1.

I've got a fork running on 4.0. Maybe you'd consider merging?

### CODE REVIEW

**Comment by kleinrein** [comment]
Hey. Thanks for the PR. 

That's right, I will accept the merge, great additions.

I am currently on holiday so I can't update the nuget package until next week.

**Comment by atruskie** [comment]
Hi, thanks for merging 😄 

I apologise for putting two commits in the pull request - I should know better than to make changes on master.

No rush for the Nuget package (it turns out MyGet works exceptionally well).

**Comment by kleinrein** [comment]
Myget is neat! 😄 

No worries about the two commits.

**Comment by kleinrein** [comment]
Updated the nuget package now 👍

**Pull request merged**
